kind: Deployment
apiVersion: apps/v1
metadata:
  name: ksamlauth-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksamlauth-daemon
  template:
    metadata:
      labels:
        app: ksamlauth-daemon
    spec:
      containers:
        - name: ksamlauth-daemon
          image: {{ .Values.image }}
          ports:
            - containerPort: 16161
              protocol: TCP
          env:
            - name: NAMESPACE_FOR_MANAGING_SA
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IDP_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: ksamlauth-config
                  key: idp_certificate
{{ if .Values.userconfigFile }}
            - name: KSAMLAUTH_USERCONFIG
              valueFrom:
                secretKeyRef:
                  name: ksamlauth-userconfig
                  key: userconfig
{{ end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      serviceAccount: ksamlauth-sa
      serviceAccountName: ksamlauth-sa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600