kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name:  ksamlauth-daemon
spec:
  rules:
    - host: {{ .Values.ingressURL }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ksamlauth-daemon
                port:
                  number: 16161