kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksamlauth-role-control-sa-read-secrets
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - modify
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - secrets