kind: ServiceAccount
apiVersion: v1
metadata:
  name: ksamlauth-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksamlauth-role-control-sa-read-secrets
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - modify
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksamlauth-sa-control-sa-read-secrets
subjects:
  - kind: ServiceAccount
    name: ksamlauth-sa
    namespace: {{.Template.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksamlauth-role-control-sa-read-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ksamlauth-config
data:
  idp_certificate: |
    -----BEGIN CERTIFICATE-----
    {{.Template.CertificateData}}
    -----END CERTIFICATE-----
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ksamlauth-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksamlauth-daemon
  template:
    metadata:
      labels:
        app: ksamlauth-daemon
    spec:
      containers:
        - name: ksamlauth-daemon
          image: 'ghcr.io/mihail-milev/ksamlauth:4b88c2f663'
          ports:
            - containerPort: 16161
              protocol: TCP
          env:
            - name: NAMESPACE_FOR_MANAGING_SA
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IDP_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: ksamlauth-config
                  key: idp_certificate
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  serviceAccount: ksamlauth-sa
  serviceAccountName: ksamlauth-sa
---
kind: Service
apiVersion: v1
metadata:
  name: ksamlauth-daemon
spec:
  ports:
    - protocol: TCP
      port: 16161
      targetPort: 16161
  selector:
    app: ksamlauth-daemon
  type: ClusterIP
  sessionAffinity: None
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name:  ksamlauth-daemon
spec:
  rules:
    - host: {{.Template.URLToKsamlauth}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ksamlauth-daemon
                port:
                  number: 16161